version: '3'

services:
  firethorn:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  hawthorn:
    image: "nishtahir/hawthorn:latest"
    expose:
      - 4000
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - DATABASE_URL=/data/production-db.sqlite
      - AUTH_SECRET=SecretSecretsAreNoFun
      - ROCKET_ENV=development
      - ROCKET_LOG=debug
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=4000
      - LOG_CONFIG_PATH=/config/log.yml